name: Continuous Build and Deploy Railway

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup jdk 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: mvn build
        run: cd server && mvn package -DskipTests
                
      - name: Install railway
        run: |
          curl -fsSL cli.new | bash

      - name: Deploy to railway
        
        run: |
          cd server
          RAILWAY_TOKEN = $RAILWAY_TOKEN railway run
          env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT: 1f9993e2-ab07-41c4-b6a3-086203b7ee9e
