name: Continuous Build and Deploy Railway

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup jdk 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: mvn build
        run: cd server && mvn package -DskipTests
                
      - name: Install railway
        run: |
          curl -fsSL cli.new | bash

      - name: Deploy to railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd server
          echo ${RAILWAY_TOKEN} | railway login
          railway init
          railway up
